name: neotoma_pg_dump
services:
  pgneotoma:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5435:5432"
      - "5454:5454"
    expose:
      - 5432
      - 5454
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REMOTE_USER=$USERNAME
      - REMOTE_PASSWORD=$PASSWORD
      - POSTGRES_CRON_DB=${POSTGRES_CRON_DB}
    volumes:
      - ./:/home
  app:
    build:
      context: ./app
      dockerfile: app.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - pgneotoma
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REMOTE_USER=$USERNAME
      - REMOTE_PASSWORD=$PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "pgneotoma"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
    volumes:
      - ./:/home
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
